name: Deploy Application

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build Application
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'

            - name: Build with Maven
              run: mvn clean install

            - name: Login to docker hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Build docker image
              run: docker build -t gabrielwaltmann/waltmann_api:latest .

            - name: Push docker image
              run: docker push gabrielwaltmann/waltmann_api