name: Build with maven, push to docker hub and deploy at VPS

on:
  push:
    branches:
      - main

jobs:
  build-push-and-deploy:
    name: Build with maven, push to docker hub and deploy at VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
            java-version: '17'
            distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Login to docker hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: sudo docker build -f .docker/Dockerfile.prod -t gabrielwaltmann/waltmann_api:latest .

      - name: Push docker image
        run: sudo docker push gabrielwaltmann/waltmann_api

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSWORD }}
          script: |
            cd ~/gabrielwaltmann
            docker-compose pull waltmann-backend
            docker compose down waltmann-backend
            docker compose up -d --no-deps waltmann-backend
